services:
  app:
    container_name: ufm-app
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  db:
    container_name: ufm-postgresql
    image: postgis/postgis
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - volumen-ufm:/var/lib/postgresql/data

volumes:
  volumen-ufm:
    driver: local

